### PR TITLE
add macos build support

### PR DESCRIPTION
**Pull request by notedit**

### CODE REVIEW

**Comment by notedit** [comment]
fix  https://github.com/cretz/go-scrap/issues/1

**Comment by cretz** [comment]
Awesome! Thanks, will merge shortly

**Comment by caquillo07** [comment]
@notedit I tried to run the example on my Mac machine with the changes in the PR and got the error below.

Not sure if I missed something that needs to be documented, or there may be another issue there, but here is my machine's specs for reference:

macOS Mojave (10.14.2)
CPU - Intel Core i7

``` github.com/cretz/go-scrap
Undefined symbols for architecture x86_64:
  "_CFDictionaryCreate", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_CFNumberCreate", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_CFRelease", referenced from:
      _$LT$scrap..quartz..frame..Frame$u20$as$u20$core..ops..drop..Drop$GT$::drop::hc17211528444a923 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
      _$LT$scrap..quartz..capturer..Capturer$u20$as$u20$core..ops..drop..Drop$GT$::drop::h69ccd701391505f0 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
      _$LT$alloc..sync..Arc$LT$T$GT$$GT$::drop_slow::hadac4afdc200dcff in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.12.rcgu.o)
      core::ptr::real_drop_in_place::hce2b4fb8d9158d5a (.llvm.2671501705895867851) in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.10.rcgu.o)
      core::ptr::real_drop_in_place::hfada20d830aa8dde in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
      ...
  "_CFRetain", referenced from:
      scrap::quartz::frame::Frame::new::hde8cb9c94aa9813f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
  "_CGDisplayIsActive", referenced from:
      scrap::quartz::display::Display::is_active::hae9daab4160e3275 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_CGDisplayIsBuiltin", referenced from:
      scrap::quartz::display::Display::is_builtin::h3451e588cf11edd8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_CGDisplayIsMain", referenced from:
      scrap::quartz::display::Display::is_primary::h7cf6fedea65816ed in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_CGDisplayIsOnline", referenced from:
      scrap::quartz::display::Display::is_online::h44bce85f9f702ae8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_CGDisplayPixelsHigh", referenced from:
      scrap::common::quartz::Capturer::new::h7cbeafea256e598f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.3.rcgu.o)
      scrap::common::quartz::Display::height::h9c449519ed0b2dde in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.3.rcgu.o)
      scrap::quartz::display::Display::height::hc80477238e8102c7 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_CGDisplayPixelsWide", referenced from:
      scrap::common::quartz::Capturer::new::h7cbeafea256e598f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.3.rcgu.o)
      scrap::common::quartz::Display::width::h7366d65151e57009 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.3.rcgu.o)
      scrap::quartz::display::Display::width::h0de191c9cce92b0f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_CGDisplayStreamCreateWithDispatchQueue", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_CGDisplayStreamStart", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_CGDisplayStreamStop", referenced from:
      _$LT$scrap..quartz..capturer..Capturer$u20$as$u20$core..ops..drop..Drop$GT$::drop::h69ccd701391505f0 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_CGGetOnlineDisplayList", referenced from:
      scrap::quartz::display::Display::online::hd0f20250c6ebbdda in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_CGMainDisplayID", referenced from:
      scrap::common::quartz::Display::primary::h519c1fbc47b91143 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.3.rcgu.o)
      scrap::quartz::display::Display::primary::hfbb19e9c7489d0a9 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.4.rcgu.o)
  "_IOSurfaceDecrementUseCount", referenced from:
      _$LT$scrap..quartz..frame..Frame$u20$as$u20$core..ops..drop..Drop$GT$::drop::hc17211528444a923 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      _$LT$alloc..sync..Arc$LT$T$GT$$GT$::drop_slow::hadac4afdc200dcff in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.12.rcgu.o)
      core::ptr::real_drop_in_place::hce2b4fb8d9158d5a (.llvm.2671501705895867851) in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.10.rcgu.o)
      core::ptr::real_drop_in_place::hfada20d830aa8dde in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
  "_IOSurfaceGetAllocSize", referenced from:
      scrap::quartz::frame::Frame::new::hde8cb9c94aa9813f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
  "_IOSurfaceGetBaseAddress", referenced from:
      scrap::quartz::frame::Frame::new::hde8cb9c94aa9813f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
  "_IOSurfaceIncrementUseCount", referenced from:
      scrap::quartz::frame::Frame::new::hde8cb9c94aa9813f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
  "_IOSurfaceLock", referenced from:
      scrap::quartz::frame::Frame::new::hde8cb9c94aa9813f in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
  "_IOSurfaceUnlock", referenced from:
      _$LT$scrap..quartz..frame..Frame$u20$as$u20$core..ops..drop..Drop$GT$::drop::hc17211528444a923 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.14.rcgu.o)
      _$LT$alloc..sync..Arc$LT$T$GT$$GT$::drop_slow::hadac4afdc200dcff in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.12.rcgu.o)
      core::ptr::real_drop_in_place::hce2b4fb8d9158d5a (.llvm.2671501705895867851) in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.10.rcgu.o)
      core::ptr::real_drop_in_place::hfada20d830aa8dde in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
      _$LT$X$u20$as$u20$block..IntoConcreteBlock$LT$$LP$A$C$$u20$B$C$$u20$C$C$$u20$D$RP$$GT$$GT$::into_concrete_block::concrete_block_invoke_args4::h1575056e5ea38263 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.5.rcgu.o)
  "_kCFBooleanFalse", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_kCFBooleanTrue", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_kCFTypeDictionaryKeyCallBacks", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_kCFTypeDictionaryValueCallBacks", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_kCGDisplayStreamMinimumFrameTime", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_kCGDisplayStreamPreserveAspectRatio", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_kCGDisplayStreamQueueDepth", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
  "_kCGDisplayStreamShowCursor", referenced from:
      scrap::quartz::capturer::Capturer::new::h94f490dc3a15dee8 in libscrap_sys.a(scrap-0f0f32419b0ca37e.scrap.36jra8yl-cgu.6.rcgu.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by notedit** [comment]
It seems  the added  framework does not work for you.  You can try to  make a clean build. 

It works for me.

**Comment by cretz** [comment]
Merging

**Pull request merged**
